# Generated by Django 4.0.4 on 2022-06-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_rename_your_name_login_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('post_type', models.CharField(choices=[('Online marketing', 'Online marketing'), ('social media', 'social media'), ('technology', 'technology'), ('writting', 'writting')], max_length=20)),
            ],
        ),
    ]
