# Generated by Django 4.0.5 on 2022-07-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
